/*
 * mundiapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package invoices_pkg

import "mundiapi_lib/models_pkg"

/*
 * Interface for the INVOICES_IMPL
 */
type INVOICES interface {
    CancelInvoice (string) (*models_pkg.GetInvoiceResponse, error)

    GetLastInvoiceCharge (string) (*models_pkg.GetChargeResponse, error)

    GetInvoices () (*models_pkg.ListInvoicesResponse, error)

    GetInvoice (string) (*models_pkg.GetInvoiceResponse, error)
}

/*
 * Factory for the INVOICES interaface returning INVOICES_IMPL
 */
func NewINVOICES() INVOICES {
    return &INVOICES_IMPL{}
}