/*
 * mundiapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package orders_pkg

import "time"
import "mundiapi_lib/configuration_pkg"
import "mundiapi_lib/models_pkg"

/*
 * Interface for the ORDERS_IMPL
 */
type ORDERS interface {
    UpdateOrderStatus (string, *models_pkg.UpdateOrderStatusRequest, *string) (*models_pkg.OrdersClosedResponse, error)

    DeleteAllOrderItems (string, *string) (*models_pkg.OrdersItemsResponse, error)

    CreateOrderItem (string, *models_pkg.OrdersItemsRequest, *string) (*models_pkg.OrdersItemsResponse1, error)

    UpdateOrderMetadata (string, *models_pkg.OrdersMetadataRequest, *string) (*models_pkg.OrdersMetadataResponse, error)

    GetOrders (*int64, *int64, *string, *string, *time.Time, *time.Time, *string) (*models_pkg.OrdersResponse, error)

    CreateOrder (*models_pkg.OrdersRequest, *string) (*models_pkg.OrdersResponse1, error)

    DeleteOrderItem (string, string, *string) (*models_pkg.OrdersItemsResponse1, error)

    GetOrderItem (string, string) (*models_pkg.OrdersItemsResponse1, error)

    UpdateOrderItem (string, string, *models_pkg.OrdersItemsRequest1, *string) (*models_pkg.OrdersItemsResponse1, error)

    GetOrder (string) (*models_pkg.OrdersResponse1, error)
}

/*
 * Factory for the ORDERS interaface returning ORDERS_IMPL
 */
func NewORDERS(config configuration_pkg.CONFIGURATION) *ORDERS_IMPL {
    client := new(ORDERS_IMPL)
    client.config = config
    return client
}