/*
 * mundiapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package subscriptions_pkg

import "mundiapi_lib/models_pkg"

/*
 * Interface for the SUBSCRIPTIONS_IMPL
 */
type SUBSCRIPTIONS interface {
    UpdateSubscriptionBillingDate (string, *models_pkg.UpdateSubscriptionBillingDateRequest) (*models_pkg.GetSubscriptionResponse, error)

    CreateUsage (string, string, *models_pkg.CreateUsageRequest) (*models_pkg.GetUsageResponse, error)

    UpdateSubscriptionItem (string, string, *models_pkg.UpdateSubscriptionItemRequest) (*models_pkg.GetSubscriptionItemResponse, error)

    GetSubscriptions () (*models_pkg.ListSubscriptionsResponse, error)

    UpdateSubscriptionCard (string, *models_pkg.UpdateSubscriptionCardRequest) (*models_pkg.GetSubscriptionResponse, error)

    CreateSubscription (*models_pkg.CreateSubscriptionRequest) (*models_pkg.GetSubscriptionResponse, error)

    CreateSubscriptionItem (string, *models_pkg.CreateSubscriptionItemRequest) (*models_pkg.GetSubscriptionItemResponse, error)

    CreateDiscount (string, *models_pkg.CreateDiscountRequest) (*models_pkg.GetDiscountResponse, error)

    GetSubscription (string) (*models_pkg.GetSubscriptionResponse, error)

    UpdateSubscriptionPaymentMethod (string, *models_pkg.UpdateSubscriptionPaymentMethodRequest) (*models_pkg.GetSubscriptionResponse, error)

    GetUsages (string, string) (*models_pkg.ListUsagesResponse, error)

    DeleteUsage (string, string, string) (*models_pkg.GetUsageResponse, error)

    DeleteDiscount (string, string) (*models_pkg.GetDiscountResponse, error)

    CancelSubscription (string, *models_pkg.CreateCancelSubscriptionRequest) (*models_pkg.GetSubscriptionResponse, error)

    DeleteSubscriptionItem (string, string) (*models_pkg.GetSubscriptionItemResponse, error)
}

/*
 * Factory for the SUBSCRIPTIONS interaface returning SUBSCRIPTIONS_IMPL
 */
func NewSUBSCRIPTIONS() SUBSCRIPTIONS {
    return &SUBSCRIPTIONS_IMPL{}
}