/*
 * mundiapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package transfers_pkg

import "mundiapi_lib/configuration_pkg"
import "mundiapi_lib/models_pkg"

/*
 * Interface for the TRANSFERS_IMPL
 */
type TRANSFERS interface {
    PostCreateTransfer (*models_pkg.CreateTransfer) (*models_pkg.GetTransfer, error)

    GetTransferById (string) (*models_pkg.GetTransfer, error)

    GetTransfers1 () (*models_pkg.ListTransfers, error)
}

/*
 * Factory for the TRANSFERS interaface returning TRANSFERS_IMPL
 */
func NewTRANSFERS(config configuration_pkg.CONFIGURATION) *TRANSFERS_IMPL {
    client := new(TRANSFERS_IMPL)
    client.config = config
    return client
}